### ISSUE TITLE
YAML merge issue with Ruby 1.9.2, Rails 3 & bundler >= 1.0.10

### ISSUE THREAD

**Issue by laurynas** [bundler/bundler#1038]
I've bumped into very strange issue:
upgrading bundler to 1.0.10 caused YAML merging problem.

I have YAML file database.yml:

```
common: &common
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *common
  database: db/development.sqlite3
```

With bundler >=1.0.10 in Rails3  I'm getting error: 

```
Missing argument: database
```

This happens because of incorrect YAML merging (database: parameter gets dropped). 

I've been trying to isolate this bug for ~8 hours and finally tracked down to bundler & ruby 1.9.2. With bundler 1.0.9 it works fine, but later versions (1.0.10, 1.1.pre.1) causes this problem on ruby 1.9.2.

Tested with following configuration:

```
Ubuntu Maverick i386
rvm 1.2.6
ruby 1.9.2
rubygems 1.5.0, 1.5.2
Rails 3.0.3, 3.0.4
```
