### ISSUE TITLE
Spec failure on 1-2-stable on 1.9.3-p327

### ISSUE THREAD

**Issue by regularfry** [bundler/bundler#2223]
I check out the 1-2-stable branch at 3cc68d4c40e91f5f0743d1be99476bc8cfe6dc4a, run rake spec:deps and rake spec, and I get:

```
Failures:

  1) gemcutter's dependency API when Gemcutter API takes too long to respond times out and falls back on the modern index
     Failure/Error: expect(out).to include("\nFetching full source index from #{@server_uri}")
     ArgumentError:
       wrong number of arguments (1 for 0)
     # /home/zander/.rvm/gems/ruby-1.9.3-p327/gems/rspec-expectations-2.8.0/lib/rspec/matchers/block_aliases.rb:15:in `expect'
     # /home/zander/00-projects/47-justin/bundler/spec/install/gems/dependency_api_spec.rb:205:in `block (3 levels) in <top (required)>'
     # /home/zander/.rvm/gems/ruby-1.9.3-p327/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:80:in `instance_eval'
     # /home/zander/.rvm/gems/ruby-1.9.3-p327/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:80:in `block in run'
     # /home/zander/.rvm/gems/ruby-1.9.3-p327/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:173:in `with_around_hooks'
     # /home/zander/.rvm/gems/ruby-1.9.3-p327/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:77:in `run'
     # /home/zander/.rvm/gems/ruby-1.9.3-p327/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:355:in `block in run_examples'
     # /home/zander/.rvm/gems/ruby-1.9.3-p327/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:351:in `map'
     # /home/zander/.rvm/gems/ruby-1.9.3-p327/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:351:in `run_examples'
     # /home/zander/.rvm/gems/ruby-1.9.3-p327/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:337:in `run'
     # /home/zander/.rvm/gems/ruby-1.9.3-p327/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `block in run'
     # /home/zander/.rvm/gems/ruby-1.9.3-p327/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `map'
     # /home/zander/.rvm/gems/ruby-1.9.3-p327/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `run'
     # /home/zander/.rvm/gems/ruby-1.9.3-p327/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /home/zander/.rvm/gems/ruby-1.9.3-p327/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `map'
     # /home/zander/.rvm/gems/ruby-1.9.3-p327/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `block in run'
     # /home/zander/.rvm/gems/ruby-1.9.3-p327/gems/rspec-core-2.8.0/lib/rspec/core/reporter.rb:34:in `report'
     # /home/zander/.rvm/gems/ruby-1.9.3-p327/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:25:in `run'
     # /home/zander/.rvm/gems/ruby-1.9.3-p327/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:80:in `run_in_process'
     # /home/zander/.rvm/gems/ruby-1.9.3-p327/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:69:in `run'
     # /home/zander/.rvm/gems/ruby-1.9.3-p327/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:10:in `block in autorun'

Finished in 452.85 seconds
712 examples, 1 failure, 1 pending

```

```
 $ rvm -v

rvm 1.17.2 (stable) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
```
