### ISSUE TITLE
Bundler breaks when using Psych 2.0.9 and Rubinius

### ISSUE THREAD

**Issue by YorickPeterse** [bundler/bundler#3348]
Psych 2.0.9 added a feature where it dumps `Hash` instances with instance variables if any are present. For example:

```ruby
require 'psych'

Psych.dump(:a => 10) # => "---\n:a: 10\n"

hash = {:a => 10}

hash.instance_variable_set(:@number, 20)

Psych.dump(hash) # => "--- !ruby/hash-with-ivars\nelements:\n  :a: 10\nivars:\n  :@number: 20\n"
```

On Rubinius the `Hash` class has a bunch of instance variables used for its internal state (since `Hash` is pure Ruby). This seems to result in `.bundle/config` files ending up with contents such as the following after a `bundle install --deployment`:

```
--- !ruby/hash-with-ivars
elements:
  BUNDLE_FROZEN: '1'
  BUNDLE_PATH: vendor/bundle
  BUNDLE_DISABLE_SHARED_GEMS: '1'
ivars:
  :@mask: 15
  :@entries: !ruby/object:Rubinius::Tuple {}
  :@capacity: 16
  :@max_entries: 12
  :@state: &1 !ruby/object:Hash::State
    compare_by_identity: false
    head: &3 !ruby/object:Hash::Bucket
      value: '1'
      next: &2 !ruby/object:Hash::Bucket
        value: vendor/bundle
        next: &4 !ruby/object:Hash::Bucket
          value: '1'
          key: BUNDLE_DISABLE_SHARED_GEMS
          key_hash: 3956570515860004216
          link: 
          state: *1
          previous: *2
        key: BUNDLE_PATH
        key_hash: 1339943540124309747
        link: 
        state: *1
        previous: *3
      key: BUNDLE_FROZEN
      key_hash: 4407484451883449113
      link: 
      state: *1
    tail: *4
  :@size: 3
```

This in turn causes problems such as the one described in https://github.com/rubinius/rubinius/issues/3284 (which I'm closing in favour of this issue).

The problem appears to be Bundler manually parsing YAML files, instead of just using YAML: https://github.com/bundler/bundler/blob/a2343c9eabf5403d8ffcbca4dea33d18a60fc157/lib/bundler/settings.rb#L158

See the following Psych issue for more info: https://github.com/tenderlove/psych/issues/216
