### ISSUE TITLE
minitest in .bundle not generating correct Rakefile

### ISSUE THREAD

**Issue by gaustin** [bundler/bundler#3673]
This is a bug in 1.9.9 and confirmed to be fixed in 1.10.0.rc1.
With a `.bundle/config` in my home directory:
```yaml
---
BUNDLE_GEM__COC: true
BUNDLE_GEM__MIT: true
BUNDLE_GEM__TEST: minitest
```

The Rakefile generated for `bundle gem foo` is missing the minitest test task configuration:
```ruby
require "bundler/gem_tasks"
```

When it should be something like:
```ruby
require "bundler/gem_tasks"
require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList['test/**/*_test.rb']
end

task :default => :test
```

I'm not sure if this is worth patching in 1.9.9 if the 1.10.0 release is immenent.
