### ISSUE TITLE
"cannot load such file" @bundler 1.16.2 with old ruby version.

### ISSUE THREAD

**Issue by LarsFronius** [bundler/bundler#6537]
Not sure if the issue is isolated to old ruby versions, but one of our customers does:
```
$ rvm use 2.0.0 --install
Using /home/rof/.rvm/gems/ruby-2.0.0-p648
YAML safe loading is not available. Please upgrade psych to a version that supports safe loading (>= 2.0).

$ gem install bundler
YAML safe loading is not available. Please upgrade psych to a version that supports safe loading (>= 2.0).
Fetching: bundler-1.16.2.gem (100%)
Successfully installed bundler-1.16.2
1 gem installed

$ bundle exec parallel_test
4 processes for 40 specs, ~ 10 specs per process
/home/rof/.rvm/gems/ruby-2.0.0-p648/bin/bundle:23:in `load': cannot load such file -- /home/rof/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/gems/2.0.0/gems/bundler-1.16.2/exe/bundle (LoadError)
	from /home/rof/.rvm/gems/ruby-2.0.0-p648/bin/bundle:23:in `<main>'
	from /home/rof/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
	from /home/rof/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'
/home/rof/.rvm/gems/ruby-2.0.0-p648/bin/bundle:23:in `load': cannot load such file -- /home/rof/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/gems/2.0.0/gems/bundler-1.16.2/exe/bundle (LoadError)
	from /home/rof/.rvm/gems/ruby-2.0.0-p648/bin/bundle:23:in `<main>'
	from /home/rof/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
	from /home/rof/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'
/home/rof/.rvm/gems/ruby-2.0.0-p648/bin/bundle:23:in `load': cannot load such file -- /home/rof/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/gems/2.0.0/gems/bundler-1.16.2/exe/bundle (LoadError)
	from /home/rof/.rvm/gems/ruby-2.0.0-p648/bin/bundle:23:in `<main>'
	from /home/rof/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
	from /home/rof/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'
/home/rof/.rvm/gems/ruby-2.0.0-p648/bin/bundle:23:in `load': cannot load such file -- /home/rof/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/gems/2.0.0/gems/bundler-1.16.2/exe/bundle (LoadError)
	from /home/rof/.rvm/gems/ruby-2.0.0-p648/bin/bundle:23:in `<main>'
	from /home/rof/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
	from /home/rof/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'
/home/rof/.rvm/gems/ruby-2.0.0-p648/bin/bundle:23:in `load': cannot load such file -- /home/rof/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/gems/2.0.0/gems/bundler-1.16.2/exe/bundle (LoadError)
	from /home/rof/.rvm/gems/ruby-2.0.0-p648/bin/bundle:23:in `<main>'
	from /home/rof/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
	from /home/rof/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'
/home/rof/.rvm/gems/ruby-2.0.0-p648/bin/bundle:23:in `load': cannot load such file -- /home/rof/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/gems/2.0.0/gems/bundler-1.16.2/exe/bundle (LoadError)
	from /home/rof/.rvm/gems/ruby-2.0.0-p648/bin/bundle:23:in `<main>'
	from /home/rof/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
	from /home/rof/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'
/home/rof/.rvm/gems/ruby-2.0.0-p648/bin/bundle:23:in `load': cannot load such file -- /home/rof/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/gems/2.0.0/gems/bundler-1.16.2/exe/bundle (LoadError)
	from /home/rof/.rvm/gems/ruby-2.0.0-p648/bin/bundle:23:in `<main>'
	from /home/rof/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
	from /home/rof/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'
/home/rof/.rvm/gems/ruby-2.0.0-p648/bin/bundle:23:in `load': cannot load such file -- /home/rof/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/gems/2.0.0/gems/bundler-1.16.2/exe/bundle (LoadError)
	from /home/rof/.rvm/gems/ruby-2.0.0-p648/bin/bundle:23:in `<main>'
	from /home/rof/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
	from /home/rof/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'
```

This reproducibly worked in bundler 1.16.1.

**Comment by chrisbarber86** [comment]
We see the same issue with Ruby 2.3.0:

```
/home/rof/cache/bundler/bin/bundle:104:in `load': cannot load such file -- /home/rof/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/exe/bundle (LoadError)
	from /home/rof/cache/bundler/bin/bundle:104:in `<main>'
```

**Comment by thbar** [comment]
I've seen something similar on a client using CircleCI parallel builds:

```
/usr/local/bundle/bin/bundle:23:in `load': cannot load such file -- /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/exe/bundle (LoadError)
	from /usr/local/bundle/bin/bundle:23:in `<main>'
```

This is with Docker and Ruby 2.3.7.

Reverting to Bundler 1.16.1 fixes the issue.

Partial CircleCI setup for the record:

```yaml
version: 2
jobs:
  build:
    docker:
      # https://circleci.com/docs/2.0/circleci-images/#ruby
      # NOTE: stretch refers to the current "Debian" stable
      - image: circleci/ruby:2.3.7-stretch
    parallelism: 2
    steps:
      - checkout
      # some code uses the "look" command
      - run: sudo apt-get install bsdmainutils
      # Covers against CVEs in rubygems
      - run: gem update --system
      # We're meeting failures with 1.16.2 on CircleCI
      - run: gem install bundler --version 1.16.1
      - restore_cache:
          keys:
            - gem-cache-{{ checksum "Gemfile.lock" }}
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out test_results/rspec.xml \
                            --format progress $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
```

**Comment by colby-swandale** [comment]
A small repo to reproduce this issue for us would be a huge help.

**Comment by hsbt** [comment]
@LarsFronius @thbar Can you reproduce it without parallel execution? I couldn't find related changes by quick code review in `v1.16.1...v1.16.2`.

**Comment by thbar** [comment]
@hsbt I also got the error after using `parallelism: 1`.

@colby-swandale I will try to create a small reproduction on CircleCI + GitHub once my consulting day is done (unless someone already provided something in the mean time).

**Comment by colby-swandale** [comment]
Can you also attach the output of `bundle env`

**Comment by thbar** [comment]
@colby-swandale will do!

**Comment by thbar** [comment]
Here is a reproduction:

* https://github.com/thbar/repro-bundler-issue-6537/tree/master
* CI run available at https://travis-ci.org/thbar/repro-bundler-issue-6537

To trigger the error, I had to shell out to `bundler --version` [from a spec](https://github.com/thbar/repro-bundler-issue-6537/blob/master/spec/sample_spec.rb), but at this point I'm not sure yet this is strictly required (this was the easiest path to reproduce the issue, since my client's code specs do shell out to issue call to "bundle exec" during specs, since we're doing complicated integration testing on a Ruby command line).

**Comment by thbar** [comment]
Changes are visible at https://github.com/bundler/bundler/compare/v1.16.1...v1.16.2 (to make it easier for someone to have a look).

**Comment by thbar** [comment]
One last note for now: I only get failures on CI (docker / ubuntu), but could not get to trigger a failure locally (Mac, be with 2.3.7 or 2.5.1).

**Comment by thbar** [comment]
In the case of @LarsFronius, I believe it may also be a matter of shelling out to `bundle exec`, after looking quickly here:

https://github.com/grosser/parallel_tests/blob/1a748aa9c50034c9dac0d9f104e54299eb00ef23/lib/parallel_tests/rspec/runner.rb#L22

**Comment by AustinWinstanley** [comment]
Same error. Ruby versions 2.3.3 and 2.3.6.

**Comment by bobziuchkovski** [comment]
Same error for us with ruby 2.4.4p296.  Reverting to 1.16.1 resolved for us as well.

```/usr/local/bundle/bin/bundle:104:in `load': cannot load such file -- /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.2/exe/bundle (LoadError)```

**Comment by colby-swandale** [comment]
Thanks for the input everyone, I've been looking into this issue but have not had much success in reproducing this issue on my machine. Any more information about your environment would be a huge help. Is this only happening in CI for everyone? What's the output of `bundle env`. Thanks :bowing_man:

**Comment by bobziuchkovski** [comment]
@colby-swandale Thanks for looking into this.

I think this might have to do with bundle path overrides.  I can reliably reproduce using @thbar 's example if I `bundle install --path=vendor/bundle`, whereas I cannot reproduce if I don't specify that path.

You can verify locally with docker if you'd like.  Adding a `Dockerfile` to a clone of @thbar 's [repository](https://github.com/thbar/repro-bundler-issue-6537) with the below content and building/running, will fail the spec.  Changing the `bundle install --path=vendor/bundle` to a bare `bundle install` causes the spec to pass again.

**Dockerfile**:
```
FROM ruby:2.4

WORKDIR /usr/src/app

RUN gem install bundler -v 1.16.2

COPY . .

# Fails when --path is specified
RUN bundle install --path=vendor/bundle

# Succeeds when --path is not specified
#RUN bundle install

CMD [ "bundle", "exec", "rspec" ]
```

Reproduce with `docker build -t repro . && docker run --rm -it repro`

**Comment by AustinWinstanley** [comment]
@colby-swandale I've only reproduced on GitLab CI so far.

```
image: "ruby:2.3.6"

stages:
  - test

cache:
  paths:
    - vendor

test:
  stage: test
  script:
  - apt-get update -qq && apt-get install -yqq libxi6 libgconf-2-4 chromedriver libjpeg-dev libpng12-dev g++ gcc liblzma-dev libreadline-dev beanstalkd sqlite3 libsqlite3-dev curl libcurl3 libcurl3-gnutls libcurl4-openssl-dev libssl-dev libxml2 libxml2-dev libxslt1.1 libxslt-dev make pkg-config patch xml-core xvfb zlib1g-dev zlibc
  - cp config/database.ci.yml config/database.yml
  - ln -s /usr/lib/chromium/chromedriver /usr/bin/chromedriver
  - chmod +x /usr/bin/chromedriver
  - service beanstalkd start
  - gem install bundler --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor/bundle
  - mkdir -p ./tmp
  - RAILS_ENV=test bundle exec rake test
```

Replacing 

`gem install bundler --no-ri --no-rdoc` 

with 

`gem install bundler --no-ri --no-rdoc -v '1.16.1'` 

works just fine.
