### ISSUE TITLE
Question about Azure

### ISSUE THREAD

**Issue by bernikovich** [bundler/bundler#7299]
Is it possible right now to use `bundler` in `Azure Pipelines`?

**Comment by deivid-rodriguez** [comment]
Yes, of course.

To use ruby, here you have some docs: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-ruby-version?view=azure-devops

Once you have ruby in your pipeline, in order to use bundler, you just have to install it with `gem install bundler`.

**Comment by bernikovich** [comment]
@deivid-rodriguez I'll try adding `bundler` this way. Thanks.

**Comment by deivid-rodriguez** [comment]
Ok, let me know if you run into issues!

**Comment by bernikovich** [comment]
I don't know how does MS search work on their website, but I just found an article (https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/ruby?view=azure-devops) which contains following steps:
```yaml
- script: |
    CALL gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'
```
```yaml
- script: bundle exec rake
  displayName: 'bundle exec rake'
```
